### ISSUE TITLE
Cyrillic file names harmed

### ISSUE THREAD

**Issue by AlexeyAG** [znuny/Znuny4OTRS-DownloadAllAttachments#3]
Hi!
I am tring to use this plugin, but Cyrillic file names harmed within zip file.
Did you test it with non latin file names ?

**Comment by thorsteneckel** [comment]
Hi @AlexeyAG 

Could you provide a example file that's affected by this issue so we can reproduce it? We once had an issue with Mandarin but thats already fixed.

Greetings,
  Thorsten

**Comment by AlexeyAG** [comment]
![default](https://cloud.githubusercontent.com/assets/12947471/10334211/8e4fe0c4-6cf1-11e5-9452-39f81a8f4172.png)
This file may have the name "Безымянный.png" - Use this cyrrilic String to create file on your PC.
Is this information enogh ?

**Comment by thorsteneckel** [comment]
Hi @AlexeyAG 

Thanks! I tried to reproduce this on one of our VirtualZnuny instances but it works like it should.

Could you please check if it works for you, too?

http://vz584.demo.znuny.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=2
User: agent-1
Password: agent-1

**Comment by AlexeyAG** [comment]
Result of opening zip file in 7zip and windows explorer in attachments
![znuny](https://cloud.githubusercontent.com/assets/12947471/10335104/6cae176e-6cf7-11e5-9d02-cd33c1f4afd6.png)
![znuny-explorer](https://cloud.githubusercontent.com/assets/12947471/10335194/be230a64-6cf7-11e5-91f6-c13de11d843e.png)

ch

**Comment by thorsteneckel** [comment]
Thanks for the provided feedback. It seems this issue is caused by the windows clients or the perl module "Archive::Zip" we use for compression. There is a (four year old) bug in the bugtracker of the module:

https://rt.cpan.org/Public/Bug/Display.html?id=75052

It seems the issue is out of reach for us and I can't help you any further.
