### ISSUE TITLE
Kernel::Output::HTML::TicketMenu::Generic doesn't exist

### ISSUE THREAD

**Issue by k-mx** [znuny/Znuny4OTRS-DownloadAllAttachments#5]
Change:
Kernel::Output::HTML::TicketMenu::Generic to Kernel::Output::HTML::TicketMenuGeneric
in
Kernel/Config/Files/Znuny4OTRSDownloadAllAttachments.xml

**Comment by rkaldung** [comment]
Maybe the same here? Kernel::Output::HTML::TicketMenu::Generic is OTRS 5, Kernel::Output::HTML::TicketMenuGeneric OTRS 4.

**Comment by k-mx** [comment]
Sorry! I switched to wrong branch. Thx
