### ISSUE TITLE
No interpolation

### ISSUE THREAD

**Issue by k-mx** [znuny/Znuny4OTRS-DownloadAllAttachments#7]
File: Kernel/Modules/AgentTicketDownloadAllAttachments.pm

$Filename .= ' ($AttachmentNames{ $Filename })';

**Comment by rkaldung** [comment]
Hi,

Please provide more details what you problem is. If you believe there's something wrong in the code: create a pull request.

Thank you

**Comment by jepf** [comment]
Hi @k-mx ,

thank you for reporting this. It's fixed now.

**Comment by jepf** [comment]
@k-mx 

Sorry, I didn't see your pull request :-(
